<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="coverlet.collector" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExpenseManager.Core\ExpenseManager.Core.csproj" />
    <ProjectReference Include="..\ExpenseManager.Infrastructure\ExpenseManager.Infrastructure.csproj" />
    <ProjectReference Include="..\ExpenseManager.ExternalServices\ExpenseManager.ExternalServices.csproj" />
    <ProjectReference Include="..\ExpenseManager.Service\ExpenseManager.Service.csproj" />
    <ProjectReference Include="..\ExpenseManager.Web\ExpenseManager.Web.csproj" />
  </ItemGroup>

</Project>
